config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  resources :buys
  resources :productclients
  root 'welcome#index'

end

app/models/buy.rb
class Buy < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
has_many :buys
has_many :users, :through => :buys
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :buys
has_many :products, :through => :buys
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
	 def new
    @buy = Buy.new
  end
end

app/controllers/productclients_controller.rb
class ProductclientsController < ApplicationController
	def index
  @products = Product.all
  end
def new
    @buy = Buy.new
  end
  def create
  	@buy = Buy.new(buy_params)
 
    if @buy.save
      redirect_to productclients_path
      else
        
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
		 def new
    @product = Product.new
  end
 ##############################################
  def create
  	@product = Product.new(product_params)
 
    if @product.save
      redirect_to @product
      else
        render'new'
    end
  end
#########################################
  def show
  	@product = Product.find(params[:id])
  end
#########################################
  def index
  @products = Product.all
  end
#############################

  
#############################
def edit
  @product = Product.find(params[:id])
end

def update
  @product = Product.find(params[:id])
 
  if @product.update(product_params)
    redirect_to @product
  else
    render 'edit'
  end
end
########################################################
def destroy
  @product = Product.find(params[:id])
  @product.destroy
 
  redirect_to products_path
end
#######################################################
 private
  def product_params
    params.require(:product).permit(:code, :name, :stock)
  end
#################################################################
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/helpers/productclients_helper.rb
module ProductclientsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/buys/index.html.erb
<div class="container">

<h1 class="text-success">Lista de compras</h1>
 
<div class="table-responsive">
    <table class="table  table-hover table-condensed">
        
  <thead>

  <tr class="active">
    <th>id compra</th>
    <th>id usuario</th>
    <th>id producto</th>
    
  </tr>
 </thead>
 <tbody>
   <% @buys.each do |buy| %>
    <tr class="success text-verdana">
      <td><%= buy.id %></td>
      <td><%= buy.iduser %></td>
      <td><%= buy.idproduct %></td>

     
    </tr>
  <% end %>


 </tbody>



    </table>

  </div>
</div>


<%= link_to 'Nueva compra', productclients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Car</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/productclients/index.html.erb
<% if user_signed_in? %>
<div class="container">

<h1 class="text-success">Lista de Productos</h1>
 
<div class="table-responsive">
    <table class="table  table-hover table-condensed">
        
  <thead>

  <tr class="active">
    <th>Codigo</th>
    <th>Nombre</th>
    <th>Existencia</th>
  </tr>
 </thead>
 <tbody>
   <% @products.each do |product| %>
    <tr class="success text-verdana">
      <td><%= product.code %></td>
      <td><%= product.name %></td>
      <td><%= product.stock %></td>
      <td><input type="checkbox" name="option3" value="<%= product.code %>"> <%= product.id %></td>


      
    </tr>
  <% end %>


 </tbody>



    </table>

  </div>
</div>
<%else%>
<p><%= link_to "Crear una cuenta", new_user_registration_path %></p>
<p>Si ya tienes cuenta: <%= link_to "Logeate", new_user_session_path %></p>
<%end%>

app/views/productclients/index2.html.erb
<% if user_signed_in? %>
<div class="container">

<h1 class="text-success">Lista de Productos</h1>
 
<div class="table-responsive">
    <table class="table  table-hover table-condensed">
        
  <thead>

  <tr class="active">
    <th>Codigo</th>
    <th>Nombre</th>
    <th>Existencia</th>
  </tr>
 </thead>
 <tbody>
   <% @products.each do |product| %>
    <tr class="success text-verdana">
      <td><%= product.code %></td>
      <td><%= product.name %></td>
      <td><%= product.stock %></td>
      <td></td>
      
      <td>
        
          <%= form_for @buy, html: {class: 'form-horizontal'} do |f| %>

    

  <div class="field">
    <%= f.check_box :iduser, checked: "checked", value="<%= current_user.id %>", style="display:none;" %>
    
  </div>
                            

 <div class="field"> 
    <%= f.checkbox :idproduct, type="checkbox", name="option4", value="<%= product.id %>", style="display:none;" %>

     
    </div>
  <%= f.submit class: 'btn btn-primary' %>
                 
<% end %>



      </td>


      
    </tr>
  <% end %>


 </tbody>



    </table>

  </div>
</div>
<p><%= link_to "ver carrito de compras", buy_path %></p>
<%else%>
<p><%= link_to "Crear una cuenta", new_user_registration_path %></p>
<p>Si ya tienes cuenta: <%= link_to "Logeate", new_user_session_path %></p>
<%end%>

app/views/products/_form.html.erb
<%= form_for @product, html: {class: 'form-horizontal'} do |f| %>

  	<% if @product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited
              this article from being saved:</h2>
        <ul>
              <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :codigo, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    	<%= f.text_field :code, class: 'form-control' %>
    </div>
  </div>
 														<br>

 <div class="form-group"> 
    <%= f.label :Nombre, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">	
    	<%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  														<br>
  <div class="form-group">
    <%= f.label :existencia, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    <%= f.text_field :stock, class: 'form-control' %>
    </div>
  </div>

  	<div class="actions form-group">
    	<div class="col-sm-offset-2 col-sm-10">
  			<%= f.submit class: 'btn btn-primary' %>
		</div>
	</div>
<% end %>
</div>

app/views/products/edit.html.erb
<div class="container">
<h1 class="text-success">Modificar Producto</h1>
<br><br>

<%= render 'form' %>
 
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container">

<h1 class="text-success">Lista de Productos</h1>
 
<div class="table-responsive">
    <table class="table  table-hover table-condensed">
        
  <thead>

  <tr class="active">
    <th>Codigo</th>
    <th>Nombre</th>
    <th>Existencia</th>
  </tr>
 </thead>
 <tbody>
   <% @products.each do |product| %>
    <tr class="success text-verdana">
      <td><%= product.code %></td>
      <td><%= product.name %></td>
      <td><%= product.stock %></td>

      <td><%= link_to 'Ver', product_path(product) %></td>
    <td><%= link_to 'Modificar', edit_product_path(product) %></td>
    <td><%= link_to 'Eliminar', product_path(product),
                    method: :delete, data: { confirm: 'Esta seguro de eliminar Producto?' } %></td>
    </tr>
  <% end %>


 </tbody>



    </table>

  </div>
</div>


<%= link_to 'Nuevo Producto', new_product_path %>

app/views/products/index2.html.erb
<%= link_to 'Nuevo Producto', new_product_path %>

app/views/products/new.html.erb
<div class="container">
<br><br>

<h1 class="text-success">Registrar nuevo Producto</h1>

<br>
<%= render 'form' %>
 
<%= link_to 'Back', products_path %>         

 

app/views/products/show.html.erb
<p>
  <strong>Codigo:</strong>
  <%= @product.code %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Existencia:</strong>
  <%= @product.stock %>
</p>

<%= link_to 'Back', products_path %>

app/views/welcome/index.html.erb
<h1>INICIO DE PAGINA</h1>
<% if user_signed_in?  &&  (current_user.email)=='admin@example.com'%> 

<%= link_to 'Nuevo Producto', new_product_path %>

<%end%>
<% if user_signed_in? %>
<p>Bienvenido: <%= current_user.email %></p>
<p><%= link_to "Ver productos", productclients_path %></p>
<p><%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %></p>



<%else%>
<p><%= link_to "Crear una cuenta", new_user_registration_path %></p>
<p>Si ya tienes cuenta: <%= link_to "Logeate", new_user_session_path %></p>

<%end%>

app/views/welcome/index2.html.erb
<h1>USUARIO YA INICIO SECION</h1>
<% if user_signed_in? %>

<%= current_user.email %>

<%end%>